### ISSUE TITLE
Rabbit Hole - no victims yet

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#124]
http://z5jixbfejdu5wtxd2baliu6hwzgcitlspnttr7c2eopl5ccfcjrhkqid.onion/

Tox

8B4D8279ADF4C78A71252B32FCF00CC395C08D3C082D185E1604FE2E4950C66D31EC3D51AA4B

**Comment by JMousqueton** [comment]
Thank you, 

It was added yesterday : https://ransomware.live/#/group/rabbithole
