### ISSUE TITLE
Last 8base victim - RSHP, not detected 

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#126]

**Comment by JMousqueton** [comment]
RSHP was detected and added few hours ago 


![image](https://github.com/JMousqueton/ransomware.live/assets/4148567/4661e400-a651-443c-bc7b-b33b2f86b55d)


` {
        "post_title": "RSHP",
        "group_name": "8base",
        "discovered": "2024-03-18 04:22:55.043312",
        "description": "We are RSHP, an architectural practice creating sustainable places for a better future. RSHP is an award-winning, 180-strong architectural practice, operating globallyrshp.com",
        "website": "rshp.com",
        "published": "2024-02-14 00:00:00.000000",
        "post_url": "http://xb6q2aggycmlcrjtbjendcnnwpmmwbosqaugxsqb4nx6cmod3emy7sad.onion/company/7890386",
        "country": "GB"
    },`

**Comment by JMousqueton** [comment]
I guess I know why ...  I used the attack date for <pubdate> so check at 2024-02-14
