### ISSUE TITLE
I am having difficulty cloning the project on vercel as it gives me screenshot error

### ISSUE THREAD

**Issue by Ayesha420420** [JMousqueton/ransomware.live#13]
this is the error code about : visit page and take screenshot

**Comment by JMousqueton** [comment]
I don't use Vercel, and the code has not been made for it. 
Ransomware.live is running now on a dedicated server

**Comment by Ayesha420420** [comment]
so for deployment of this project, I would need my dedicated server or can be done through github ?

**Comment by JMousqueton** [comment]
You can use a VM (any linux with python3).
