### ISSUE TITLE
FLocker group

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#150]
FLocker group

flock4cvoeqm4c62gyohvmncx6ck2e7ugvyqgyxqtrumklhd5ptwzpqd.onion

**Comment by JMousqueton** [comment]
Commit https://github.com/JMousqueton/ransomware.live/commit/825553342ed43281d3e73eb3f3e747e221d53b35

Group Added
Parser Written 
Victims added
