### ISSUE TITLE
Telegram channel 

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#16]
Hello everyone!

 I've set up a Telegram channel featuring all the latest Ransomware Live posts. 

Feel free to join and share:

 https://t.me/ransomwarelive

**Comment by ErezDasa** [comment]
BTW @JMousqueton, as you can see the text is:

Xxxx has just published a NOW post: Yyyy

Can you fix it so it will be New instead of Now?

**Comment by JMousqueton** [comment]
I've corrected the typo and re generate the RSS feed.

**Comment by JMousqueton** [comment]
I would appreciate if you add the link from the RSS Feed

**Comment by ErezDasa** [comment]
Sure, Where do you want me to put the link?

**Comment by JMousqueton** [comment]
there is a field <link> for every item in the RSS feed

**Comment by ErezDasa** [comment]
OK  let me check

**Comment by ErezDasa** [comment]
OK  let me check think of found it.
I added the vje to each message.

Is there any problem with the rss feed? No new posts since yesterday

**Comment by ErezDasa** [comment]
> thanks, found a bug in the RSS generator for vicitms without post_url ... corrected : https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.ransomware.live%2Frss.xml 

Looks good now.
I've just added the URL for each message, let me know if that OK.

**Comment by JMousqueton** [comment]
Thanks !!!
