### ISSUE TITLE
Screenshot URL in API/JSON

### ISSUE THREAD

**Issue by markus-lassfolk** [JMousqueton/ransomware.live#2]
Hi, would it be possible for you to include the URL to the screenshot in the JSON and API Response for recent victims?

**Comment by JMousqueton** [comment]
Hi Markus, 

I will include this feature in the api v2.0 (for now I'm developing v1.0)

**Comment by JMousqueton** [comment]
Finally I've just added it to the API 

https://github.com/JMousqueton/api.ransomware.live/commit/a3ae64e589ca4e548567dd135233160d8b065d5e
