### ISSUE TITLE
Helldown group

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#206]
http://onyxcgfg4pjevvp5h34zvhaj45kbft3dg5r33j5vu3nyp7xic3vrzvad.onion/

**Comment by JMousqueton** [comment]
Thank you as usual. 

Parser added : https://github.com/JMousqueton/ransomware.live/commit/ea6f4ced4ddf36e9b566c2c64c00f5b2714d47a9

Parsing in processing on the website
