### ISSUE TITLE
Orca group

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#227]
http://orca66hwnpciepupe5626k2ib6dds6zizjwuuashz67usjps2wehz4id.onion

**Comment by JMousqueton** [comment]
Thank you so much.

Group added : https://www.ransomware.live/group/orca
Parser written and first victim in the database : https://www.ransomware.live/id/RXhjZWxQbGFzdCBUdW5pc2llQG9yY2E=
