### ISSUE TITLE
8base down

### ISSUE THREAD

**Issue by nuke86** [JMousqueton/ransomware.live#237]
The site has been down for a long time, you can add this working link for 8base to the monitoring

http://92.118.36.204/

**Comment by JMousqueton** [comment]
Thank you so much
added and victims added to our database

**Comment by nuke86** [comment]
8base gang is again down. New working URL is:
hxxp://xfycpauc22t5jsmfjcaz2oydrrrfy75zuk6chr32664bsscq4fgyaaqd.onion/

**Comment by JMousqueton** [comment]
added
