### ISSUE TITLE
InterLock

### ISSUE THREAD

**Issue by nuke86** [JMousqueton/ransomware.live#238]
New gang onion DLS:
http://ebhmkoohccl45qesdbvrjqtyro2hmhkmh6vkyfyjjzfllm3ix72aqaid.onion/

Leaks are on this page: http://ebhmkoohccl45qesdbvrjqtyro2hmhkmh6vkyfyjjzfllm3ix72aqaid.onion/leaks.php

**Comment by JMousqueton** [comment]
Thank you, I've added this new gang to the database. 
Parser written and first victim added to database.
