### ISSUE TITLE
Akira leaks section

### ISSUE THREAD

**Issue by nuke86** [JMousqueton/ransomware.live#254]
there are a significant number of Akira claims that are not detected because they are outside the "news" section. The criminals are also filing inside the "leaks" section
![photo_2024-11-14_21-43-17](https://github.com/user-attachments/assets/98603332-f336-4feb-8ad1-bcf2a02c29d0)

**Comment by JMousqueton** [comment]
Thank you I've added it, but I need to clean the database.  We'll do today
