### ISSUE TITLE
Ransomexx

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#27]
http://rnsm777cdsjrsdlbs4v5qoeppu3px6sb2igmh53jzrx7ipcrbjz5b2ad.onion/

**Comment by JMousqueton** [comment]
What's the issue with Ransomexx ? 

It's already referenced and parsed by ransomware.live : https://www.ransomware.live/#/group/ransomexx

**Comment by ErezDasa** [comment]
Sorry, my bad. You can ignore this.
