### ISSUE TITLE
Track Clop torrents site

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#29]
I saw that other projects started track this site under "clop torrents"

http://toznnag5o3ambca56s2yacteu7q7x2avrfherzmz4nmujrjuib4iusad.onion/

**Comment by JMousqueton** [comment]
Yes but there are still Clop victims. 

This site is also parsed by ransomware.live but most victims was already reported by Clop main site.  

I’ve decided not to add two times the same victims from the same cyberattack : MoveIT
