### ISSUE TITLE
URL miss spelled in Screeenshot Attribute in API

### ISSUE THREAD

**Issue by markus-lassfolk** [JMousqueton/ransomware.live#3]
The New Screenshot attribute in API has a type-o

Notice the miss spelled "ransomare.live" vs "ransomware.live" 
https://images.ransomare.live/screenshots/posts/ded19993434d96d46a0d6e9afccb4157.png
https://images.ransomare.live/screenshots/posts/8479c28ef1ce9070df876f464ccc6fa1.png
https://images.ransomare.live/screenshots/posts/a00a949769b35b53fc9824cec9b8dc8d.png
https://images.ransomare.live/screenshots/posts/4eec243d938b824f253e2f3783199dc3.png
https://images.ransomare.live/screenshots/posts/d92a193b480d5837c625307aeb11968c.png

**Comment by JMousqueton** [comment]
Corrected https://github.com/JMousqueton/api.ransomware.live/commit/af7464a16aa1464b053feead1f9f5902ad4a8e18
