### ISSUE TITLE
Pictures in the rss feed

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#38]
Is it possible to add the ransom group post images in the rss feed?

**Comment by JMousqueton** [comment]
It's already the case when a picture is available 

`<item>
<title>🏴‍☠️ Incransom has just published a new victim : Federal Labor Relations Authority</title>
<link>https://www.ransomware.live/#/group/incransom</link>
<description>The Federal Labor Relations Authority (FLRA) is an independent agency of the United States government that governs labor relations between the federal government and its employees.</description>
<enclosure url="https://images.ransomware.live/screenshots/posts/d5e6fefc7d0a8a44d88a265df8318414.png" type="image/png" length="237538"/>
<guid>https://www.ransomware.live/#/group/incransom?24f286344d8ac9af999f642bd420028f</guid>
<pubDate>Wed, 20 Sep 2023 14:31:33 +0000</pubDate>
</item>`

**Comment by ErezDasa** [comment]
Ohh I missing it, thanks!

**Comment by JMousqueton** [comment]
Welcome ;)
