### ISSUE TITLE
Navigation issue on website related to screenshots

### ISSUE THREAD

**Issue by markus-lassfolk** [JMousqueton/ransomware.live#4]
Looks like it's not possible to access the image without first acquiring a web-browser session. 

Steps to reproduce: 
1. Open a browser, for example Edge 
2. Navigate to https://ransomware.live/#/recentposts 
3. Click on the eyes symbol to see the screenshot
4. It's visible as expected 
5. Copy the URL to clipboard 
6. Open another browser, for example Chrome
7. Paste the image URL from clipboard 
8. Expected result is to see the image but you get redirected to https://www.ransomware.live/#/ instead

**Comment by JMousqueton** [comment]
I've blocked request to images.ransomware.live without referer. 
It's now remove
you should access images
