### ISSUE TITLE
LostTrust issue

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#48]
Hi, seems like LostTrust has not been added to the site, rss, etc.
You added them in commit 46 but can't find it elsewhere

Thanks!

**Comment by JMousqueton** [comment]
The victims of losttrust are [here](https://ransomware.live/#/group/losttrust)

and this is an extract of the [rss feed](https://ransomware.live/rss) 

`<title>🏴‍☠️ Losttrust has just published a new victim : Arazoza Brothers</title>
<link>https://www.ransomware.live/#/group/losttrust</link>
<description>Arazoza Brothers is Florida’s leading Commercial Landscape company. We take pride in delivering consistently excellent results for clients across the state, throughout the lifespan of their landscapes.</description>
<enclosure url="https://www.ransomware.live/ransomwarelive.png" type="image/png" length="36922"/>
<guid>https://www.ransomware.live/#/group/losttrust?4bbb01cc32770abaea45c8336ef37788</guid>
<pubDate>Tue, 26 Sep 2023 11:10:43 +0000</pubDate>
</item>`

**Comment by ErezDasa** [comment]
Thank you! I didn't find them under group profiles because it comes after the letter Z =)

**Comment by JMousqueton** [comment]
My bad, I forgot to reorder ;) 

I'll do now
