### ISSUE TITLE
RSS Feed per group

### ISSUE THREAD

**Issue by muelli** [JMousqueton/ransomware.live#55]
I would appreciate an Atom or RSS feed per group rather than one big feed for all groups as it is now.

**Comment by JMousqueton** [comment]
Hi, 

I add it to my ToDo list

You can use the API per group instead : https://api.ransomware.live

**Comment by JMousqueton** [comment]
Hi Muelli,

I've done it 

https://www.[ransomware.live/grouprss/](https://www.ransomware.live/grouprss/) 

is it fine for you ?

**Comment by muelli** [comment]
Excellent! Thank you so much!
