### ISSUE TITLE
Chat negotiations rss

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#61]
Hi @JMousqueton, is there any way to pull the chat negotiations through rss?

Thanks!

Erez.

**Comment by ErezDasa** [comment]
It will be awesome! I really appreciate that.

**Comment by JMousqueton** [comment]
Can you check https://www.ransomware.live/negotiations.xml  ?

**Comment by ErezDasa** [comment]
It looks good.
It doesn't include the chat itself, right? Only a notification that a new negotiation has been added with a link to the chat in the site. Correct me if I'm wrong.

**Comment by JMousqueton** [comment]
True, it's complicated to add the chat.

**Comment by ErezDasa** [comment]
Great, thanks for that. I appreciate that a lot and I'll continue supporting you as much as I can.

Erez
