### ISSUE TITLE
Play ransomware - latest victims

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#63]
Hi @JMousqueton, in the last play blitz they published 17 new victims.
For some reason RansomwareLive counts only 12.

I checked and it seems that all the victims in their 2nd page were not counted. I'm attaching a picture of these victims.

![Screenshot_2023-11-29-08-59-37-648_org.torproject.torbrowser.jpg](https://github.com/JMousqueton/ransomware.live/assets/52123771/278c9c29-42b5-4ac8-a78a-470ebbc07220)

Thanks!

**Comment by JMousqueton** [comment]
Hi,

It should be corrected by now. 
Thank you so much for noticing me this problem

Julien

**Comment by ErezDasa** [comment]
Thank YOU!
