### ISSUE TITLE
Cloak

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#66]
Hi @JMousqueton

I think there is some issues with the Cloak group parser. no detected victims since August and there has been a few victims since then.

Also, want to check with you about the negotiations rss, I saw that a new negotiation chat added here lately

https://github.com/Casualtek/Ransomchats/

But nothing came up in the rss feed.

Thank you!

**Comment by JMousqueton** [comment]
regarding the ransomchats I'm sync. Last commit of chat is oct-26

For Cloak there is a captcha, I'm looking if it will be possible to bypass it ... neverless for now I've update manually.

**Comment by ErezDasa** [comment]
Thank you!
