### ISSUE TITLE
Recent Victims RSS/API

### ISSUE THREAD

**Issue by Arcuza** [JMousqueton/ransomware.live#70]
Is it possible to add an RSS or API for this:

https://ransomware.live/#/recentvictims

Response including:

- Date
- Title
- Country
- Group
- URL to Screenshot

Thank you very much for your hard work!

**Comment by ErezDasa** [comment]
It will be great to see the country value in the rss feeds 😊

**Comment by JMousqueton** [comment]
@Arcuza  : Api already returns these information, 

See : https://api.ransomware.live/apidocs/ 

Example : 

  {
    "country": "CN",
    "description": "Our in-house discovery team focuses on the discovery of novel therapeutics in oncology and autoimmune diseases. Zai Lab has built a strong global development team with extensive experience in key functional areas, including preclinical and clinical d...",
    "discovered": "2023-12-11 09:59:22.085011",
    "group_name": "lockbit3",
    "post_title": "zailaboratory.com",
    "post_url": "http://lockbitapt2d73krlbewgv27tquljgxr33xbwwsp6rkyieto7u4ncead.onion/post/OyobjO7p5SFEJgWS6576d2c069f0c",
    "published": "2023-12-11 09:13:00.000000",
    "screenshot": "https://images.ransomware.live/screenshots/posts/52bf59aad9be2f8e1682f08da114ee47.png",
    "website": ""
  },

@ErezDasa  
I'll see how to add country to RSS Feed in the next days ...

**Comment by Arcuza** [comment]
Thanks @JMousqueton.

**Comment by JMousqueton** [comment]
Country add at the end of the title in the RSS Feed
