### ISSUE TITLE
Ransomed vc sites are back online

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#71]
Also, I think there is an issue with Lorenz parser, last victim not detected

**Comment by JMousqueton** [comment]
I'll check for Ransomedvc 

Regarding lorenz, which victim  ? Bayer Heritage Federal Credit Union ?  if yes it presents at the date 01/12/22 (the one published by Lorenz) 
I'vemanually corrected to 2023.

**Comment by ErezDasa** [comment]
Yes this one
 Bayer Heritage Federal Credit Union

Ohh OK, I didn't see it in the rss feed.

Thanks!

**Comment by JMousqueton** [comment]
Regarding RANSOMED.VC aka Raznatovic they only sell old leak for now.  I'll continue to monitor but I won't publish for now.
