### ISSUE TITLE
New Group - DragonForce

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#73]
http://z3wqggtxft7id3ibr7srivv5gjof5fwg76slewnzwwakjuf3nlhukdid.onion/blog

**Comment by JMousqueton** [comment]
done

**Comment by nuke86** [comment]
There is an error in this scraper, parsing the "website" URL field. The website is repeated the same (like first post) in all posts of DragonForce.

**Comment by JMousqueton** [comment]
Corrected.  Thank you
