### ISSUE TITLE
Cactus last victims

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#76]
Hi, any issues with Cactus? Last victims were not detected (dillarddoor.com for example)

**Comment by JMousqueton** [comment]
Hi, 

This victim are present : 

![image](https://github.com/JMousqueton/ransomware.live/assets/4148567/9d6e9089-4ddf-4bf3-b01b-924054d757b8)

source : https://ransomware.live/#/group/cactus 

Discovered on 2023-12-15 15:29:55.100894 under the name DILLARD (with "website": "www.dillarddoor.com",)  and on 2023-12-13 11:33:13.613737 under the name Dillard Door & Security

**Comment by ErezDasa** [comment]
My bad. I missed that. I searched the rss feed for http://www.dillarddoor.com

Thanks!

**Comment by JMousqueton** [comment]
Don't worry
