### ISSUE TITLE
Alphv working site

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#78]
http://alphvuzxyxv6ylumd2ngp46xzq3pw6zflomrghvxeuks6kklberrbmyd.onion

**Comment by JMousqueton** [comment]
already added thought issue https://github.com/JMousqueton/ransomware.live/issues/77 but thank you ;)

**Comment by ErezDasa** [comment]
Ohh I checked in the site before writing here and it wasn't there =)

**Comment by JMousqueton** [comment]
It was there but "offline" thank you, you found a bug in rendering the webpage ;)

I've corrected it 

Thank again and my appologies !!!

**Comment by ErezDasa** [comment]
Thank YOU!
