### ISSUE TITLE
Duplicates in rss

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#81]
Hi @JMousqueton, since you updated the rss to includes countries, there are a lot of duplicate notifications, one without the country and another include the country, for example: goldenc.com by Lockbit.

**Comment by JMousqueton** [comment]
I've reverse the code.  

But the xml file contained only one entry and Guid stay the same. Should be a reader/parser problem.

**Comment by ErezDasa** [comment]
Thanks!

**Comment by JMousqueton** [comment]
Now the country is in the category field of the RSS feed
