### ISSUE TITLE
Noname site is up but the status in ransomware.live is down

### ISSUE THREAD

**Issue by ErezDasa** [JMousqueton/ransomware.live#91]
http://noname2j6zkgnt7ftxsjju5tfd3s45s4i3egq5bqtl72kgum4ldc6qyd.onion/

**Comment by JMousqueton** [comment]
Sorry I'm not sure to understand what you mean

**Comment by JMousqueton** [comment]
it is recognized as up : 
![image](https://github.com/JMousqueton/ransomware.live/assets/4148567/d6ccc044-eed2-4ac6-bb1e-cbf479a9dd6d)
